server:
  address: 0.0.0.0
  port: ${PORT:8080}
spring:
  profiles.active: ${ACTIVE_PROFILE:dev}
  jpa:
    hibernate:
      ddl-auto: update
  influxdb:
      url: http://80.211.29.54:8086
      database: data
      username: user
      password: ~
      retention-policy: autogen

management:
   security:
      enabled: true

auth:
   internal:
      user: ${USER:admin}
      pass: ${PASS:admin}

---
spring:
  profiles: dev
  h2:
    console:
      enabled: true
      path: ${H2_PATH:/h2}
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:file:~/spring-boot-h2-db}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:}
    driver-class-name: org.h2.Driver
logging:
  file: logs/pingservice_dev.log
  level:
    org.springframework.web: DEBUG
    ru.javazen.telegram.bot: DEBUG
    org.hibernate: DEBUG
---
spring:
  profiles: production
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
logging:
  file: logs/pingservice_prod.log
  level:
    org.springframework.web: WARN
    ru.javazen.telegram.bot: WARN
    org.hibernate: WARN


