server:
  address: 0.0.0.0
  port: ${PORT:8080}
spring:
  profiles.active: ${ACTIVE_PROFILE:dev}
  jpa:
    hibernate:
      ddl-auto: update
  influxdb:
      url: ${INFLUX_URL:http://80.211.29.54:8086}
      database: ${INFLUX_DB:data}
      username: ${INFLUX_USER:user}
      password: ${INFLUX_PASS:~}
      retention-policy: autogen

management:
   security:
      enabled: true

auth:
   internal:
      user: ${USER:admin}
      pass: ${PASS:admin}

cors:
  allowed-origins: ${ALLOWED_ORIGINS:}


bot:
  enabled: ${BOT_ENABLED:true}
  config:
    silentPeriod: ${SILENTPERIOD:10}
    proxy:
      host: ${PROXY_HOST:}
      port: ${PROXY_PORT:}
      user: ${PROXY_USER:}
      pass: ${PROXY_PASS:}
  credential:
    telegram:
      login: ${TELEGRAM_BOT_NAME:}
      token: ${TELEGRAM_BOT_TOKEN:}
    admin:
      user: ${ADMIN_USER_NAME:admin}
      pass: ${ADMIN_USER_PASS:admin}


---
spring:
  profiles: dev
  h2:
    console:
      enabled: true
      path: ${H2_PATH:/h2}
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:file:~/spring-boot-h2-db}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:}
    driver-class-name: org.h2.Driver
logging:
  file: logs/pingservice_dev.log
  level:
    org.springframework.web: DEBUG
    ru.javazen.telegram.bot: DEBUG
    org.hibernate: DEBUG
---
spring:
  profiles: production
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
logging:
  file: logs/pingservice_prod.log
  level:
    org.springframework.web: WARN
    ru.javazen.telegram.bot: WARN
    org.hibernate: WARN


